version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - mongo
    restart: always
    environment:
      MONGODB_URI: mongodb://mongo:27017/mydb?authSource=mydb
      SECRET_KEY: japaitarmhasecrettummai-secretyounii
      EMAIL_USER: fog3kp@gmail.com
      EMAIL_PASS: dpzzdqqknbgthibm

  frontend:
    build:
      context: ./frontend
      args:
        VITE_ENDPOINT: http://backend:3000
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - backend

  dashboard:
    build:
      context: ./dashboard
      args:
        VITE_ENDPOINT: http://backend:3000
    ports:
      - "5174:5174"
    volumes:
      - ./dashboard:/app
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
volumes:
  mongo_data:
