version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "3001:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
    - ./backend/uploads:/app/uploads
    env_file:
      - ./backend/.env
    networks:
      - app-network
    depends_on:
      - mongo
    restart: always

  frontend:
    build:
      context: ./frontend
      args:
        VITE_ENDPOINT: http://backend:3000
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - backend

  dashboard:
    build:
      context: ./dashboard
      args:
        VITE_ENDPOINT: http://backend:3000
    ports:
      - "5174:5174"
    networks:
      - app-network
    depends_on:
      - backend

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongo_data:
    external: true
